<a href="https://colab.research.google.com/github/sanjeetkumar989159-hub/Data_wrangling-cleaning/blob/main/Data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/hr_employee_messy_dataset.csv')
print(df)

     EmployeeID FirstName  LastName  Gender   Age        Department  \
0      EMP04426      Juan    Harper    male  39.0        OPERATIONS
1      EMP01802    Tanner   Holland    Male  24.0         marketing
2      EMP01585    Dennis    Moreno  FEMALE  44.0        Operations
3      EMP00245   Stephen  Martinez     Mle  24.0             SALES
4      EMP03895  Benjamin    Austin       F  25.0  customer support
...         ...       ...       ...     ...   ...               ...
5375   EMP04308   Nichole   Stevens       F  21.0  Customer Support
5376   EMP02551      Chad    Cannon     Mle  22.0              H.R.
5377   EMP00538   Cynthia    Fowler    Male  36.0        OPERATIONS
5378   EMP01221     Kathy   Hubbard  Female  29.0   Human Resources
5379   EMP04272       Amy     Silva  Female  38.0                IT

            State         City       JoiningDate  YearsExperience      Salary  \
0      Tamil Nadu   Coimbatore        27-08-2021              5.2  Rs. 97,038
1       Telangana    hyderabad        2019-03-22              6.8  Rs. 84,600
2     West Bengal      KOLKATA        2026-03-03              1.2  Rs. 39,869
3     Maharashtra         Pune       27 Sep 2021              5.3    77675.54
4      Tamil Nadu      Chennai        2025-02-17              0.9       31978
...           ...          ...               ...              ...         ...
5375  Maharashtra         pune        2019-11-03              8.0  Rs. 83,145
5376   Tamil Nadu      Chennai        18/03/2022              6.2  Rs. 41,369
5377  West Bengal     durgapur       04 May 2022              4.5       34288
5378  West Bengal      Kolkata  January 03, 2022              4.2    42331.58
5379    Karnataka    Bengaluru        26-10-2017              9.4  Rs. 76,608

     MaritalStatus  PerformanceRating            ManagerName AttritionStatus  \
0         Divorced                5.0        Lauren Parks MD              no
1         Divorced                2.0  Dr. Stephanie Shields              No
2          Marreid                3.0            Peter Lewis              No
3           single                4.0             Adam Craig              no
4         DIVORCED                3.0              Eric Hull              No
...            ...                ...                    ...             ...
5375        Single                4.0                    NaN              no
5376        SINGLE                2.0       Melissa Mcdonald              no
5377        single                4.0          Patrick Lopez               N
5378       Marreid                3.0                    NaN              NO
5379         Sngle                3.0        Morgan Gonzalez               Y

      EngagementScore  WorkHoursPerWeek                            Email  \
0                 NaN              42.0        juan.harper89@company.com
1                74.6              51.9    tanner.holland661@company.com
2                89.3              43.1     dennis.moreno338@company.com
3                 NaN              43.9  stephen.martinez524@company.com
4                76.2              44.0   benjamin.austin461@company.com
...               ...               ...                              ...
5375             77.6              40.9   nichole.stevens327@company.com
5376             73.3              34.6       chad.cannon342@company.com
5377             81.4              48.7    cynthia.fowler778@company.com
5378             75.2              39.6     kathy.hubbard877@company.com
5379             70.7              38.7         amy.silva258@company.com

                 PhoneNumber
0      001-370-404-6660x5226
1      001-403-232-7399x7415
2     001-477-873-0316x78719
3         (791)755-9428x4347
4          412-964-0535x2932
...                      ...
5375   001-977-918-6986x8301
5376        930-367-7798x367
5377    001-782-296-3533x905
5378      (432)301-6290x7399
5379              6034902915

[5380 rows x 19 columns]

# data understanding

In [ ]:
df.shape

(5380, 19)

In [ ]:
df.tail()

,EmployeeID,FirstName,LastName,Gender,Age,Department,State,City,JoiningDate,YearsExperience,Salary,MaritalStatus,PerformanceRating,ManagerName,AttritionStatus,EngagementScore,WorkHoursPerWeek,Email,PhoneNumber
5375,EMP04308,Nichole,Stevens,F,21.0,Customer Support,Maharashtra,pune,2019-11-03,8.0,"Rs. 83,145",Single,4.0,NaN,no,77.6,40.9,nichole.stevens327@company.com,001-977-918-6986x8301
5376,EMP02551,Chad,Cannon,Mle,22.0,H.R.,Tamil Nadu,Chennai,18/03/2022,6.2,"Rs. 41,369",SINGLE,2.0,Melissa Mcdonald,no,73.3,34.6,chad.cannon342@company.com,930-367-7798x367
5377,EMP00538,Cynthia,Fowler,Male,36.0,OPERATIONS,West Bengal,durgapur,04 May 2022,4.5,34288,single,4.0,Patrick Lopez,N,81.4,48.7,cynthia.fowler778@company.com,001-782-296-3533x905
5378,EMP01221,Kathy,Hubbard,Female,29.0,Human Resources,West Bengal,Kolkata,"January 03, 2022",4.2,42331.58,Marreid,3.0,NaN,NO,75.2,39.6,kathy.hubbard877@company.com,(432)301-6290x7399
5379,EMP04272,Amy,Silva,Female,38.0,IT,Karnataka,Bengaluru,26-10-2017,9.4,"Rs. 76,608",Sngle,3.0,Morgan Gonzalez,Y,70.7,38.7,amy.silva258@company.com,6034902915

In [ ]:
df.head()

,EmployeeID,FirstName,LastName,Gender,Age,Department,State,City,JoiningDate,YearsExperience,Salary,MaritalStatus,PerformanceRating,ManagerName,AttritionStatus,EngagementScore,WorkHoursPerWeek,Email,PhoneNumber
0,EMP04426,Juan,Harper,male,39.0,OPERATIONS,Tamil Nadu,Coimbatore,27-08-2021,5.2,"Rs. 97,038",Divorced,5.0,Lauren Parks MD,no,NaN,42.0,juan.harper89@company.com,001-370-404-6660x5226
1,EMP01802,Tanner,Holland,Male,24.0,marketing,Telangana,hyderabad,2019-03-22,6.8,"Rs. 84,600",Divorced,2.0,Dr. Stephanie Shields,No,74.6,51.9,tanner.holland661@company.com,001-403-232-7399x7415
2,EMP01585,Dennis,Moreno,FEMALE,44.0,Operations,West Bengal,KOLKATA,2026-03-03,1.2,"Rs. 39,869",Marreid,3.0,Peter Lewis,No,89.3,43.1,dennis.moreno338@company.com,001-477-873-0316x78719
3,EMP00245,Stephen,Martinez,Mle,24.0,SALES,Maharashtra,Pune,27 Sep 2021,5.3,77675.54,single,4.0,Adam Craig,no,NaN,43.9,stephen.martinez524@company.com,(791)755-9428x4347
4,EMP03895,Benjamin,Austin,F,25.0,customer support,Tamil Nadu,Chennai,2025-02-17,0.9,31978,DIVORCED,3.0,Eric Hull,No,76.2,44.0,benjamin.austin461@company.com,412-964-0535x2932

# Data inspection

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.columns = df.columns.str.replace(' ', '_').str.strip().str.lower()

In [ ]:
df.columns

# Data cleaning

In [ ]:
print(df['age'].dtype)

In [ ]:
df['age'] = df['age'].fillna(df['age'].mode()[0])

In [ ]:
df.isnull().sum()

In [ ]:
df['yearsexperience'] = df['yearsexperience'].fillna(df['yearsexperience'].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df.head()

,employeeid,firstname,lastname,gender,age,department,state,city,joiningdate,yearsexperience,salary,maritalstatus,performancerating,managername,attritionstatus,engagementscore,workhoursperweek,email,phonenumber
0,EMP04426,Juan,Harper,male,39,OPERATIONS,Tamil Nadu,Coimbatore,27-08-2021,5.2,NaN,Divorced,5.0,Lauren Parks MD,no,NaN,42.0,juan.harper89@company.com,001-370-404-6660x5226
1,EMP01802,Tanner,Holland,Male,24,marketing,Telangana,hyderabad,2019-03-22,6.8,NaN,Divorced,2.0,Dr. Stephanie Shields,No,74.6,51.9,tanner.holland661@company.com,001-403-232-7399x7415
2,EMP01585,Dennis,Moreno,FEMALE,44,Operations,West Bengal,KOLKATA,2026-03-03,1.2,NaN,Marreid,3.0,Peter Lewis,No,89.3,43.1,dennis.moreno338@company.com,001-477-873-0316x78719
3,EMP00245,Stephen,Martinez,Mle,24,SALES,Maharashtra,Pune,27 Sep 2021,5.3,77675.54,single,4.0,Adam Craig,no,NaN,43.9,stephen.martinez524@company.com,(791)755-9428x4347
4,EMP03895,Benjamin,Austin,F,25,customer support,Tamil Nadu,Chennai,2025-02-17,0.9,31978.00,DIVORCED,3.0,Eric Hull,No,76.2,44.0,benjamin.austin461@company.com,412-964-0535x2932

# Data inspection

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5380 entries, 0 to 5379
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         5380 non-null   object
 1   FirstName          5380 non-null   object
 2   LastName           5380 non-null   object
 3   Gender             5380 non-null   object
 4   Age                5217 non-null   float64
 5   Department         5380 non-null   object
 6   State              5380 non-null   object
 7   City               5380 non-null   object
 8   JoiningDate        5380 non-null   object
 9   YearsExperience    5275 non-null   float64
 10  Salary             5216 non-null   object
 11  MaritalStatus      5277 non-null   object
 12  PerformanceRating  5001 non-null   float64
 13  ManagerName        4739 non-null   object
 14  AttritionStatus    5380 non-null   object
 15  EngagementScore    5107 non-null   float64
 16  WorkHoursPerWeek   5380 non-null   float64
 17  Email              5380 non-null   object
 18  PhoneNumber        4950 non-null   object
dtypes: float64(5), object(14)
memory usage: 798.7+ KB

In [ ]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age', 'Department',
       'State', 'City', 'JoiningDate', 'YearsExperience', 'Salary',
       'MaritalStatus', 'PerformanceRating', 'ManagerName', 'AttritionStatus',
       'EngagementScore', 'WorkHoursPerWeek', 'Email', 'PhoneNumber'],
      dtype='object')

In [ ]:
df.describe()

,Age,YearsExperience,PerformanceRating,EngagementScore,WorkHoursPerWeek
count,5217.000000,5275.000000,5001.000000,5107.000000,5380.000000
mean,34.046387,5.052474,3.010198,69.540787,45.449833
std,9.559617,3.030256,1.421723,14.549280,10.619272
min,-5.000000,0.000000,1.000000,20.400000,2.000000
25%,28.000000,2.500000,2.000000,59.650000,41.000000
50%,34.000000,5.100000,3.000000,69.900000,45.000000
75%,39.000000,7.500000,4.000000,79.700000,49.100000
max,150.000000,13.100000,5.000000,100.000000,200.000000

In [ ]:
df.isnull().sum()

EmployeeID             0
FirstName              0
LastName               0
Gender                 0
Age                  163
Department             0
State                  0
City                   0
JoiningDate            0
YearsExperience      105
Salary               164
MaritalStatus        103
PerformanceRating    379
ManagerName          641
AttritionStatus        0
EngagementScore      273
WorkHoursPerWeek       0
Email                  0
PhoneNumber          430
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(136)

In [ ]:
df.columns = df.columns.str.replace(' ', '_').str.strip().str.lower()

In [ ]:
df.columns

Index(['employeeid', 'firstname', 'lastname', 'gender', 'age', 'department',
       'state', 'city', 'joiningdate', 'yearsexperience', 'salary',
       'maritalstatus', 'performancerating', 'managername', 'attritionstatus',
       'engagementscore', 'workhoursperweek', 'email', 'phonenumber'],
      dtype='object')

# Data cleaning

In [1]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].astype('Int64')

NameError: name 'pd' is not defined

In [2]:
print(df['age'].dtype)

NameError: name 'df' is not defined

In [ ]:
df['age'] = df['age'].fillna(df['age'].mode()[0])

In [ ]:
df.isnull().sum()

In [ ]:
df['yearsexperience'] = df['yearsexperience'].fillna(df['yearsexperience'].mean())

In [3]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
df['salary'] = df['salary'].str.replace('Rs', ' ').str.strip()

In [4]:
print(df['salary'])

NameError: name 'df' is not defined

In [5]:
print(df['salary'].dtype)

NameError: name 'df' is not defined

In [ ]:
df.describe()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df.head()

In [6]:
df.tail()

NameError: name 'df' is not defined

In [ ]:
df.shape

In [7]:
df.describe()

NameError: name 'df' is not defined

In [8]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

In [ ]:
missing = df.isnull().sum()

In [ ]:
missing = missing[missing>0]

In [ ]:
plt.figure(figsize=(8,8))
missing.plot(kind="bar")
plt.xlabel("Columns")
plt.ylabel("Missing Values")
plt.title("Missing Values in Each Column")
plt.xticks(rotation=90)

In [ ]:
plt.plot(df.isnull().sum())
plt.xlabel("Columns")
plt.ylabel("Missing Values")
plt.title("Missing Values in Each Column")
plt.xticks(rotation=90)
plt.show()

In [ ]:
df['Age'] = df['Age'].astype('Int64')

In [ ]:
print(df['Age'].dtype)

In [ ]:

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [ ]:
mode_value = df["Age"].mode()
df["Age"].fillna(mode_value)

foerwad fill

In [ ]:
df["Age"]=df["Age"].ffill()

In [ ]:
df.Age

Backward fill

In [ ]:
df["Age"]=df["Age"].bfill()

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
df['YearsExperience'] = df['YearsExperience'].fillna(df['YearsExperience'].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df

In [ ]:
df['MaritalStatus'] = df['MaritalStatus'].fillna(df['MaritalStatus'].mode()[0])

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df['PerformanceRating'] = df['PerformanceRating'].fillna(df['PerformanceRating'].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df['ManagerName'] = df['ManagerName'].fillna(df['ManagerName'].mode()[0])

In [ ]:
df['EngagementScore'] = df['EngagementScore'].fillna(df['EngagementScore'].mean())

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
missing = df.isnull().sum()
missing = missing[missing>0]

In [ ]:
plt.figure(figsize=(5,5))
missing.plot(kind="bar")
plt.xlabel("Columns")
plt.ylabel("Missing Values")
plt.title("Missing Values in Each Column")
plt.xticks(rotation=90)

In [ ]:
df.Salary

In [9]:
df['Salary'] = df['Salary'].astype(str)

NameError: name 'df' is not defined

In [ ]:
df['Salary'] = df['Salary'].str.replace({'Rs.', '' })
df['Salary'] = df['Salary'].str.replace({',', '' })